"""AUTO-GENERATED — do not edit by hand.

Generated from the JSON Schemas in ../spec by scripts/generate.py
Run ``uv run python scripts/generate.py`` to regenerate after a schema change.

These are faithful pydantic v2 reflections of the wire schemas: snake_case Python
attributes with camelCase aliases (``populate_by_name = True``), so attribute access
is idiomatic while ``model_dump(by_alias=True)`` round-trips the camelCase wire form.
"""
# ruff: noqa
# fmt: off

# generated by datamodel-codegen:
#   filename:  _merged.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, EmailStr, Field


class SmoothAgentProtocol(BaseModel):
    model_config = ConfigDict(
        populate_by_name=True,
    )


class ErrorObject(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str
    """
    Machine-readable error code (e.g. `SESSION_NOT_FOUND`, `RATE_LIMITED`, `VALIDATION_ERROR`).
    """
    message: str
    """
    Human-readable error description.
    """


class Action(StrEnum):
    create_conversation_session = 'create_conversation_session'
    send_message = 'send_message'
    get_session = 'get_session'
    get_conversation_messages = 'get_conversation_messages'
    confirm_tool_action = 'confirm_tool_action'
    verify_otp = 'verify_otp'
    submit_interaction = 'submit_interaction'
    ping = 'ping'


class ActionEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )
    action: Action
    """
    The action to perform.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Client-generated correlation ID. Will be echoed back on all related server events. Should be unique per in-flight request. If omitted the server may generate one, but correlating responses becomes the client's problem.
    """


class Type(StrEnum):
    immediate_response = 'immediate_response'
    eventual_response = 'eventual_response'
    stream_chunk = 'stream_chunk'
    stream_token = 'stream_token'
    keepalive = 'keepalive'
    write_confirmation_required = 'write_confirmation_required'
    otp_verification_required = 'otp_verification_required'
    otp_sent = 'otp_sent'
    otp_verified = 'otp_verified'
    otp_invalid = 'otp_invalid'
    interaction_required = 'interaction_required'
    interaction_invalid = 'interaction_invalid'
    error = 'error'
    pong = 'pong'


class EventEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Type
    """
    Identifies which event this frame carries.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating action. Absent for unsolicited server-push events.
    """
    status: int | None = None
    """
    HTTP-like status code. 202 = acknowledged/in-progress; 200 = final success; 4xx/5xx = error conditions.
    """
    message: str | None = None
    """
    Optional human-readable status description (used in `immediate_response` acks).
    """
    data: dict[str, Any] | list[Any] | str | float | bool | None = None
    """
    Event-specific payload. Shape is defined by the per-event schema in `events/`.
    """
    node: str | None = None
    """
    Name of the workflow node that produced this event. Present on `stream_chunk` events.
    """
    token: str | None = None
    """
    A streamed LLM token. Present on `stream_token` events.
    """
    error: ErrorObject | None = None
    """
    Present on `error` events.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds. Present on `pong` events and optionally on others.
    """


class CancelRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['cancel']
    """
    Action discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    The requestId of the in-flight `send_message` turn to cancel. Echoed back on the `cancelled` event so the client correlates the reset.
    """
    session_id: Annotated[str | None, Field(alias='sessionId')] = None
    """
    Optional, advisory. The server cancels the connection's single active turn; a per-connection socket carries one turn at a time.
    """


class ConfirmToolActionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['confirm_tool_action']
    """
    Action discriminator.
    """
    request_id: Annotated[str, Field(alias='requestId')]
    """
    Must match the `requestId` from the `write_confirmation_required` event being responded to. This is how the server correlates the confirmation back to the paused workflow.
    """
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Session ID of the paused session.
    """
    approved: bool
    """
    True to allow the tool call to proceed; false to reject it. On rejection the agent workflow resumes with an informational context message.
    """


class ConfirmToolActionResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
        populate_by_name=True,
    )


class AuthContext(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    user_id: Annotated[str, Field(alias='userId')]
    """
    The user's identity claim.
    """
    signature: str
    """
    HMAC-SHA256 signature over `userId + timestamp` using a shared secret.
    """
    timestamp: int
    """
    Unix epoch seconds when the HMAC was signed. Used for replay protection (typical max age: 60s).
    """


class CreateConversationSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['create_conversation_session']
    """
    Action discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Client-generated correlation ID echoed back on all related events.
    """
    agent_id: Annotated[UUID, Field(alias='agentId')]
    """
    UUID of the agent to start a session with.
    """
    user_name: Annotated[str | None, Field(alias='userName')] = None
    """
    Optional display name for the user participant.
    """
    user_email: Annotated[EmailStr | None, Field(alias='userEmail')] = None
    """
    Optional email address for the user participant.
    """
    browser_fingerprint: Annotated[str | None, Field(alias='browserFingerprint')] = None
    """
    Browser fingerprint string (e.g. from ThumbmarkJS) used for anonymous user correlation across sessions.
    """
    supports: list[str] | None = None
    """
    Client render capabilities for this session — a per-kind list gating the Rich Interactions the server may emit mid-turn (`interaction_required`). Each interaction kind declares the capability that gates it (e.g. kind `identity_intake` → capability `identity_form`); future kinds add their own values (`date_picker`, `file_upload`, …). Text-only channels (SMS, voice) omit this and the server degrades each kind to its conversational fallback. Unknown values are ignored (forward-compatible).
    """
    metadata: dict[str, Any] | None = None
    """
    Arbitrary key/value metadata to attach to the session.
    """
    auth_context: Annotated[AuthContext | None, Field(alias='authContext')] = None
    """
    Pre-auth context for HMAC-based identity verification. When provided, the server can skip OTP flows by verifying the HMAC signature instead.
    """


class CreateConversationSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Newly created session ID. Use this in all subsequent actions.
    """
    conversation_id: Annotated[UUID, Field(alias='conversationId')]
    """
    ID of the conversation created for this session.
    """
    agent_id: Annotated[UUID, Field(alias='agentId')]
    """
    ID of the agent handling this session.
    """
    agent_name: Annotated[str, Field(alias='agentName')]
    """
    Display name of the agent.
    """
    user_participant_id: Annotated[UUID, Field(alias='userParticipantId')]
    """
    Participant ID representing the user in this conversation.
    """
    agent_participant_id: Annotated[UUID, Field(alias='agentParticipantId')]
    """
    Participant ID representing the AI agent in this conversation.
    """


class GetMessagesRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['get_conversation_messages']
    """
    Action discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Client-generated correlation ID echoed back on all related events.
    """
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Session ID whose conversation messages to fetch.
    """
    limit: Annotated[int | None, Field(ge=1, le=100)] = 50
    """
    Maximum number of messages to return per page. Must be 1–100; defaults to 50.
    """
    cursor: str | None = None
    """
    Opaque pagination cursor from a prior response's `nextCursor`. Returns only messages older than the one the cursor names. Treat it as opaque — its encoding is storage-defined (a message id today) and may change. Omit to start from the most recent message.

    Deliberately NOT a timestamp: two messages can share a timestamp at any precision the wire format keeps, so a `created_at < cursor` filter either drops or repeats the messages that collide. An id cursor identifies exactly one message and cannot.
    """


class Direction(StrEnum):
    inbound = 'inbound'
    outbound = 'outbound'


class Content(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    text: str | None = None
    """
    Plain-text content.
    """
    structured_response: Annotated[
        dict[str, Any] | None, Field(alias='structuredResponse')
    ] = None
    """
    Structured agent response (shape depends on agent template).
    """


class From(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    type: str
    name: str | None = None


class To(From):
    pass


class ConversationMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Unique message ID.
    """
    direction: Direction
    """
    Message direction: `inbound` = from user, `outbound` = from agent.
    """
    content: Content
    """
    Message payload. `text` contains the plain-text form; `structuredResponse` contains parsed agent output when present.
    """
    from_: Annotated[From | None, Field(alias='from')] = None
    """
    Abbreviated sender descriptor.
    """
    to: To | None = None
    """
    Abbreviated recipient descriptor.
    """
    created_at: Annotated[AwareDatetime, Field(alias='createdAt')]
    """
    ISO 8601 timestamp when the message was created.
    """


class GetSessionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['get_session']
    """
    Action discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Client-generated correlation ID echoed back on all related events.
    """
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    ID of the session to retrieve.
    """


class Status(StrEnum):
    active = 'active'
    idle = 'idle'
    ended = 'ended'


class GetSessionResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Session ID.
    """
    conversation_id: Annotated[UUID, Field(alias='conversationId')]
    """
    Conversation ID.
    """
    agent_id: Annotated[UUID, Field(alias='agentId')]
    """
    Agent ID.
    """
    agent_name: Annotated[str, Field(alias='agentName')]
    """
    Display name of the agent.
    """
    user_participant_id: Annotated[UUID, Field(alias='userParticipantId')]
    """
    Participant ID for the user in this session.
    """
    agent_participant_id: Annotated[UUID, Field(alias='agentParticipantId')]
    """
    Participant ID for the agent in this session.
    """
    thread_id: Annotated[str | None, Field(alias='threadId')] = None
    """
    smooth-operator thread identifier. Present when the session has an associated workflow thread.
    """
    status: Status | None = None
    """
    Current lifecycle status of the session.
    """


class PingRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['ping']
    """
    Action discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Client-generated correlation ID echoed back in the `pong` event.
    """


class PongResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    timestamp: int
    """
    Server-side Unix epoch milliseconds when the pong was sent.
    """


class Detail(StrEnum):
    low = 'low'
    high = 'high'
    auto = 'auto'


class Image(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    url: str
    """
    A `data:image/...;base64,...` URL or a remote `https` image URL. Emitted to the model as an OpenAI `image_url` content part.
    """
    detail: Detail | None = None
    """
    Optional OpenAI vision detail hint. Omitted when absent.
    """


class SendMessageRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['send_message']
    """
    Action discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Client-generated correlation ID echoed back on all related events.
    """
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Session ID returned by `create_conversation_session`.
    """
    message: Annotated[str, Field(max_length=10000, min_length=1)]
    """
    The user's message text. Between 1 and 10 000 characters.
    """
    stream: bool | None = True
    """
    Whether to receive incremental `stream_chunk` and `stream_token` events. Defaults to `true`. Set to `false` to receive only the final `eventual_response`.
    """
    model: str | None = None
    """
    Optional gateway model id to run THIS turn on (e.g. a /smooth-mode preset). Absent → the server's configured default model.
    """
    images: list[Image] | None = None
    """
    Optional image attachments for a multimodal turn. Each item is a `data:` or `https` image URL with an optional OpenAI vision `detail` hint. Absent/empty → a text-only turn (byte-identical to before this field existed). Fail-soft: a malformed entry is ignored rather than rejecting the turn.
    """


class ResolutionStatus(StrEnum):
    resolved = 'resolved'
    in_progress = 'in_progress'
    requires_escalation = 'requires_escalation'
    needs_more_info = 'needs_more_info'
    blocked = 'blocked'


class GeneralAgentResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    response_parts: Annotated[list[str], Field(alias='responseParts')]
    """
    Ordered text segments that together form the agent's reply. Clients may join them or render each separately.
    """
    customer_happiness_score: Annotated[
        float, Field(alias='customerHappinessScore', ge=0.0, le=1.0)
    ]
    """
    Estimated customer happiness for this turn (0 = very unhappy, 1 = very happy).
    """
    needs_satisfaction_score: Annotated[
        float, Field(alias='needsSatisfactionScore', ge=0.0, le=1.0)
    ]
    """
    Estimated degree to which the customer's needs were met (0 = not met, 1 = fully met).
    """
    request_summary: Annotated[str, Field(alias='requestSummary')]
    """
    One-sentence summary of what the user requested.
    """
    resolution_status: Annotated[ResolutionStatus, Field(alias='resolutionStatus')]
    """
    The agent's assessment of where the conversation stands after this turn.
    """
    suggested_next_actions: Annotated[list[str], Field(alias='suggestedNextActions')]
    """
    Ordered list of suggested follow-up actions the client UI may surface to the user.
    """


class SubmitInteractionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['submit_interaction']
    """
    Action discriminator.
    """
    request_id: Annotated[str, Field(alias='requestId')]
    """
    Must match the `requestId` from the `interaction_required` event being responded to.
    """
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Session ID of the parked session.
    """
    interaction_id: Annotated[str, Field(alias='interactionId')]
    """
    Must match the `interactionId` from the `interaction_required` event, so a stale submit can never resolve a newer park.
    """
    kind: str | None = None
    """
    Optional interaction kind, for cross-checking; the server already knows the parked interaction's kind. When present and mismatched, the submit is rejected.
    """
    values: dict[str, Any] | None = None
    """
    Kind-specific submitted values. Required unless `declined` is true. Shape per `interactions/<kind>.schema.json#/$defs/Values` (e.g. identity_intake's `{ name?, email?, phone? }`). Validated server-side by the kind's validator.
    """
    declined: bool | None = None
    """
    True when the visitor refused the interaction. The turn resumes with a declined payload so the agent can proceed gracefully. When true, `values` is ignored.
    """


class SubmitInteractionResponse(ConfirmToolActionResponse):
    pass


class VerifyOtpRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    action: Literal['verify_otp']
    """
    Action discriminator.
    """
    request_id: Annotated[str, Field(alias='requestId')]
    """
    Must match the `requestId` from the `otp_verification_required` event being responded to.
    """
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Session ID of the paused session.
    """
    code: str
    """
    The one-time password code entered by the user.
    """


class VerifyOtpResponse(ConfirmToolActionResponse):
    pass


class Data(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the cancelled turn's requestId.
    """
    status: Literal[499]
    """
    Terminal cancellation status.
    """


class Cancelled(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['cancelled']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` of the cancelled `send_message` turn (falls back to the `cancel` frame's own requestId). Absent only if neither carried one.
    """
    status: Literal[499]
    """
    Terminal cancellation status ("client closed request"). Distinct from 200 (eventual_response) and from error codes.
    """
    timestamp: int | None = None
    """
    Server-side Unix epoch milliseconds when the event was emitted.
    """
    data: Data | None = None
    """
    Cancellation payload (mirrors `requestId` + `status` for clients that only inspect `data`).
    """


class Error1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str
    """
    Machine-readable error code.
    """
    message: str
    """
    Human-readable error description.
    """


class Error2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: str
    """
    Machine-readable error code (e.g. `SESSION_NOT_FOUND`, `RATE_LIMITED`, `VALIDATION_ERROR`, `INTERNAL_ERROR`).
    """
    message: str
    """
    Human-readable error description.
    """


class Data1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    The request ID this error belongs to, if any.
    """
    error: Error2
    """
    The error descriptor (nested for wire backward-compatibility).
    """
    details: dict[str, Any] | list[Any] | str | float | bool | None = None
    """
    Optional additional structured error context (e.g. validation issues, partial results).
    """


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['error']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating action, if applicable. Absent for server-initiated errors with no associated request.
    """
    error: Error1 | None = None
    """
    Top-level error object (duplicate of `data.error`; kept for clients that pattern-match on the envelope-level `error` field).
    """
    data: Data1
    """
    Full error payload.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    cost_usd: Annotated[float | None, Field(alias='costUsd')] = None
    """
    Accumulated cost in USD across every LLM call in this turn (gateway-priced).
    """
    prompt_tokens: Annotated[int | None, Field(alias='promptTokens')] = None
    """
    Accumulated prompt (input) tokens across every LLM call in this turn.
    """
    completion_tokens: Annotated[int | None, Field(alias='completionTokens')] = None
    """
    Accumulated completion (output) tokens across every LLM call in this turn.
    """


class Citation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str
    """
    Stable identifier of the cited source document (the knowledge-base `document_id`). Used to deduplicate citations within a turn.
    """
    title: str
    """
    Human-readable label for the source — typically the document's source path or, for web-sourced docs, the URL/title.
    """
    url: str | None = None
    """
    Canonical link to the source, when one exists. For GitHub-sourced documents this is the blob/issue URL stamped onto the document's `source` at ingest. Absent for sources with no web location.
    """
    snippet: str
    """
    The retrieved chunk text that grounded the answer, truncated to a bounded length for display.
    """
    score: float
    """
    Relevance score of this source for the turn's query (the knowledge-base similarity score). Higher is more relevant.
    """


class Data3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    message_id: Annotated[str, Field(alias='messageId')]
    """
    ID of the agent message as persisted to the `conversation_messages` table.
    """
    response: dict[str, Any] | list[Any] | str | float | bool | None
    """
    The structured agent response payload. Shape depends on the agent template. Clients should validate against a template-specific schema before rendering.
    """
    needs_escalation: Annotated[bool | None, Field(alias='needsEscalation')] = None
    """
    True if the agent flagged this conversation for human escalation.
    """
    escalation_reason: Annotated[str | None, Field(alias='escalationReason')] = None
    """
    Human-readable escalation reason when `needsEscalation` is true.
    """
    usage: Usage | None = None
    """
    Per-turn token accounting and cost, captured from the engine's terminal completion event. Lets a client accumulate live session cost. Optional and back-compatible: absent when the engine reported no usage for the turn (e.g. an offline/mock turn).
    """
    citations: list[Citation] | None = None
    """
    The sources that grounded this answer, when any were retrieved. Collected by the runtime from the documents that actually grounded the turn — the auto-injected `[Relevant knowledge]` context and any `knowledge_search` tool results — deduplicated by source id and capped. Optional and back-compatible: absent when the turn used no knowledge sources. Each item is a `Citation` (see `domain/citation.schema.json`).
    """
    directive: dict[str, Any] | None = None
    """
    An optional client-side directive the agent emitted for this turn (e.g. a navigation or view-application instruction). Opaque at the protocol layer — like `response`, the concrete shape (Navigate / ApplyView / …) is owned by the host client and validated there. Optional and back-compatible: absent when the turn produced no directive. Last-write-wins when multiple were emitted.
    """


class Data2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this response belongs to.
    """
    status: int
    """
    HTTP-like status. Typically 200.
    """
    data: Data3
    """
    The final agent output.
    """


class EventualResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['eventual_response']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action.
    """
    status: int | None = None
    """
    HTTP-like status. Always 200 for a successful eventual response.
    """
    data: Data2
    """
    The terminal response payload.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class ImmediateResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['immediate_response']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating action.
    """
    status: int | None = None
    """
    HTTP-like status. 202 = accepted and processing; 200 = synchronous success (non-streaming responses).
    """
    message: str | None = None
    """
    Human-readable status description (e.g. `Processing your request...`).
    """
    data: dict[str, Any]
    """
    Action-specific response payload. For `create_conversation_session` and `get_session`, this is the session descriptor. For `get_conversation_messages`, this is the message page. For streaming `send_message`, this is typically empty or contains only a minimal ack.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Error3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    field: str
    """
    The kind-specific field that failed validation.
    """
    message: str
    """
    Human-readable validation message for this field.
    """


class Data5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    interaction_id: Annotated[str, Field(alias='interactionId')]
    """
    The interaction instance the rejected submit targeted.
    """
    kind: str
    """
    The interaction kind (e.g. `identity_intake`).
    """
    errors: Annotated[list[Error3], Field(min_length=1)]
    """
    One entry per failed field. `field` is a kind-specific field key (identity_intake: `name` | `email` | `phone`).
    """
    message: str
    """
    Human-readable summary suitable for a card-level error line.
    """


class Data4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this interaction belongs to.
    """
    data: Data5
    """
    Per-field validation errors.
    """


class InteractionInvalid(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['interaction_invalid']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` of the parked turn (same correlation as the `interaction_required` event).
    """
    data: Data4
    """
    Validation failure details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data7(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    interaction_id: Annotated[str, Field(alias='interactionId')]
    """
    Server-generated ID for this specific interaction instance. Must be echoed on the `submit_interaction` reply so a stale submit can never resolve a newer park.
    """
    kind: str
    """
    The interaction kind (e.g. `identity_intake`). Selects the client's card component and the server's validator. The kind catalog lives in `spec/interactions/`.
    """
    spec: dict[str, Any]
    """
    Kind-specific render spec. Shape per `interactions/<kind>.schema.json#/$defs/Spec` (e.g. identity_intake's `{ fields: [...] }`).
    """
    reason: str
    """
    Human-readable reason the agent raised this interaction, suitable for the card header (e.g. `to send you the quote`).
    """


class Data6(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this interaction belongs to.
    """
    data: Data7
    """
    The interaction the client should render.
    """


class InteractionRequired(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['interaction_required']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action. Must be included in the `submit_interaction` reply.
    """
    data: Data6
    """
    Interaction prompt details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data8(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID of the in-flight request this keepalive belongs to.
    """


class Keepalive(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['keepalive']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    The `requestId` of the in-flight request this keepalive is associated with.
    """
    data: Data8
    """
    Keepalive payload.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the keepalive was sent.
    """


class Error4(StrEnum):
    invalid_code = 'INVALID_CODE'
    max_attempts = 'MAX_ATTEMPTS'
    not_found = 'NOT_FOUND'
    expired = 'EXPIRED'


class Data10(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    error: Error4 | None = None
    """
    Machine-readable failure reason. Absent if the server cannot determine a specific cause.
    """
    attempts_remaining: Annotated[int, Field(alias='attemptsRemaining', ge=0)]
    """
    How many more attempts the caller has before the OTP is locked. Zero means the session is locked and a new OTP must be requested.
    """
    message: str
    """
    Human-readable failure message suitable for display in the verification UI.
    """


class Data9(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this verification belongs to.
    """
    data: Data10
    """
    OTP invalid payload.
    """


class OtpInvalid(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['otp_invalid']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `verify_otp` action.
    """
    data: Data9
    """
    Failure details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Channel(StrEnum):
    email = 'email'
    sms = 'sms'


class Data12(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    channel: Channel
    """
    The channel through which the OTP was delivered.
    """
    masked_destination: Annotated[str, Field(alias='maskedDestination')]
    """
    Partially masked destination address for display in the UI (e.g. `j***@example.com` or `+1 ***-***-4567`). Sufficient for the user to recognize their own address without exposing it fully.
    """


class Data11(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this OTP delivery belongs to.
    """
    data: Data12
    """
    Delivery details.
    """


class OtpSent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['otp_sent']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating action.
    """
    data: Data11
    """
    OTP send acknowledgement details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data14(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    tool_id: Annotated[str, Field(alias='toolId')]
    """
    Opaque identifier of the tool invocation awaiting verification.
    """
    action_description: Annotated[str, Field(alias='actionDescription')]
    """
    Human-readable description of the action requiring verification, suitable for the consent UI.
    """
    available_channels: Annotated[
        list[Channel], Field(alias='availableChannels', min_length=1)
    ]
    """
    Delivery channels available to send the OTP. The client should let the user choose.
    """
    auth_level: Annotated[str, Field(alias='authLevel')]
    """
    Required authentication level. Common values: `email`, `sms`, `mfa`, `end_user`, `admin`.
    """


class Data13(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this verification belongs to.
    """
    data: Data14
    """
    Details about the authentication requirement.
    """


class OtpVerificationRequired(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['otp_verification_required']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action. Must be included in the `verify_otp` reply.
    """
    data: Data13
    """
    Verification prompt details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data16(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    message: str
    """
    Short human-readable confirmation message (e.g. `Identity verified successfully.`).
    """


class Data15(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this verification belongs to.
    """
    data: Data16
    """
    Success payload.
    """


class OtpVerified(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['otp_verified']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `verify_otp` action.
    """
    data: Data15
    """
    Verification success details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data17(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    timestamp: int
    """
    Server-side Unix epoch milliseconds.
    """


class Pong(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['pong']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `ping` action.
    """
    timestamp: int | None = None
    """
    Server-side Unix epoch milliseconds when the pong was emitted.
    """
    data: Data17 | None = None
    """
    Pong payload (mirrors top-level `timestamp` for clients that only inspect `data`).
    """


class State(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    raw_response: Annotated[
        dict[str, Any] | list[Any] | str | float | bool | None,
        Field(alias='rawResponse'),
    ] = None
    """
    Unstructured LLM output from this node, if any.
    """
    structured_response: Annotated[
        dict[str, Any] | list[Any] | str | float | bool | None,
        Field(alias='structuredResponse'),
    ] = None
    """
    Parsed structured response from this node, if any.
    """
    pending_write_confirmation: Annotated[
        dict[str, Any] | None, Field(alias='pendingWriteConfirmation')
    ] = None
    """
    Non-null when the workflow has paused awaiting user confirmation of a write operation. Clients should surface a confirmation UI.
    """
    pending_otp_verification: Annotated[
        dict[str, Any] | None, Field(alias='pendingOtpVerification')
    ] = None
    """
    Non-null when the workflow has paused awaiting OTP verification. Clients should surface an OTP input UI.
    """


class Data18(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this chunk belongs to.
    """
    node: str
    """
    Name of the workflow node that produced this state snapshot.
    """
    state: State
    """
    Filtered subset of the node's output state exposed to the client. Only safe-to-expose fields are included; server-internal state is stripped.
    """
    done: bool | None = None
    """
    Reserved for future use. When true, this is the last `stream_chunk` for the request. Currently clients should use `eventual_response` to detect stream completion.
    """


class StreamChunk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['stream_chunk']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action.
    """
    node: str | None = None
    """
    Name of the workflow node that just completed and produced this chunk.
    """
    data: Data18
    """
    The per-node state snapshot.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data19(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this preamble token belongs to.
    """
    token: str
    """
    The raw preamble token text.
    """


class StreamPreamble(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['stream_preamble']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action.
    """
    token: str | None = None
    """
    The raw preamble token text. Also present inside `data.token` for consumers that only inspect `data`.
    """
    data: Data19
    """
    Preamble token event payload.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data20(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this reasoning token belongs to.
    """
    token: str
    """
    The raw reasoning token text.
    """


class StreamReasoning(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['stream_reasoning']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action.
    """
    token: str | None = None
    """
    The raw reasoning token text. Also present inside `data.token` for consumers that only inspect `data`.
    """
    data: Data20
    """
    Reasoning token event payload.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data21(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this token belongs to.
    """
    token: str
    """
    The raw token text.
    """


class StreamToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['stream_token']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action.
    """
    token: str | None = None
    """
    The raw token text. Also present inside `data.token` for consumers that only inspect `data`.
    """
    data: Data21
    """
    Token event payload.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Data23(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    tool_id: Annotated[str, Field(alias='toolId')]
    """
    Opaque identifier of the tool invocation awaiting confirmation. Provided for correlation; clients do not need to parse or display this.
    """
    action_description: Annotated[str, Field(alias='actionDescription')]
    """
    Human-readable description of the action the agent wants to perform, suitable for displaying in a confirmation dialog (e.g. `Delete contact John Doe (john@example.com)`).
    """


class Data22(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    request_id: Annotated[str, Field(alias='requestId')]
    """
    The request ID this confirmation belongs to.
    """
    data: Data23
    """
    Details about the pending write that the user must approve or reject.
    """


class WriteConfirmationRequired(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Literal['write_confirmation_required']
    """
    Event type discriminator.
    """
    request_id: Annotated[str | None, Field(alias='requestId')] = None
    """
    Echoes the `requestId` from the originating `send_message` action. Must be included in the `confirm_tool_action` reply.
    """
    data: Data22
    """
    Confirmation prompt details.
    """
    timestamp: int | None = None
    """
    Unix epoch milliseconds when the event was emitted.
    """


class Checkpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Unique checkpoint identifier (UUID v4).
    """
    thread_id: Annotated[str, Field(alias='threadId')]
    """
    smooth-operator workflow thread identifier this checkpoint belongs to. Matches `Session.threadId` for the associated session.
    """
    agent_id: Annotated[UUID, Field(alias='agentId')]
    """
    The agent whose state is captured in this checkpoint.
    """
    iteration: Annotated[int, Field(ge=0)]
    """
    Agent loop iteration counter at the time the checkpoint was taken.
    """
    metadata: dict[str, str] | None = None
    """
    Arbitrary string key/value metadata attached to this checkpoint (e.g. phase name, bead ID).
    """
    created_at: Annotated[AwareDatetime, Field(alias='createdAt')]
    """
    ISO 8601 timestamp when the checkpoint was created.
    """


class Citation1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: str
    """
    Stable identifier of the cited source document (the knowledge-base `document_id`). Used to deduplicate citations within a turn.
    """
    title: str
    """
    Human-readable label for the source — typically the document's source path or, for web-sourced docs, the URL/title.
    """
    url: str | None = None
    """
    Canonical link to the source, when one exists. For GitHub-sourced documents this is the blob/issue URL stamped onto the document's `source` at ingest (see CONNECTORS.md). Absent for sources with no web location (e.g. uploaded files).
    """
    snippet: str
    """
    The retrieved chunk text that grounded the answer, truncated to a bounded length for display.
    """
    score: float
    """
    Relevance score of this source for the turn's query (the knowledge-base similarity score). Higher is more relevant.
    """


class Platform(StrEnum):
    web = 'web'
    messenger = 'messenger'
    instagram = 'instagram'
    email = 'email'
    discord = 'discord'
    phone = 'phone'
    sms = 'sms'
    slack = 'slack'
    whatsapp = 'whatsapp'
    tiktok = 'tiktok'


class Conversation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Unique conversation identifier.
    """
    platform: Platform
    """
    The channel on which this conversation takes place.
    """
    name: str
    """
    Human-readable display name for the conversation.
    """
    organization_id: Annotated[UUID, Field(alias='organizationId')]
    """
    The organization that owns this conversation.
    """
    idempotency_key: Annotated[str, Field(alias='idempotencyKey')]
    """
    Client-provided key that prevents duplicate conversations from being created for the same logical thread.
    """
    metadata_json: Annotated[dict[str, Any] | None, Field(alias='metadataJson')] = None
    """
    Arbitrary key/value metadata attached to the conversation (e.g. campaign source, CRM fields).
    """
    analytics_json: Annotated[dict[str, Any] | None, Field(alias='analyticsJson')] = (
        None
    )
    """
    Analytics and scoring data aggregated from messages in this conversation.
    """
    created_at: Annotated[AwareDatetime, Field(alias='createdAt')]
    """
    ISO 8601 timestamp when the conversation was created.
    """
    updated_at: Annotated[AwareDatetime, Field(alias='updatedAt')]
    """
    ISO 8601 timestamp when the conversation was last updated.
    """


class Type1(StrEnum):
    text = 'text'


class ContentItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    type: Type1
    """
    Content item type discriminator.
    """
    text: str | None = None
    """
    The text content (required when type = `text`).
    """


class From1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Participant ID of the sender.
    """
    type: str
    """
    Participant type of the sender.
    """
    name: str | None = None
    """
    Display name of the sender.
    """


class To1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Participant ID of the recipient.
    """
    type: str
    """
    Participant type of the recipient.
    """
    name: str | None = None
    """
    Display name of the recipient.
    """


class Type2(StrEnum):
    user = 'user'
    ai_agent = 'ai-agent'
    human_agent = 'human-agent'


class Participant(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Unique participant identifier.
    """
    conversation_id: Annotated[UUID, Field(alias='conversationId')]
    """
    The conversation this participant belongs to.
    """
    organization_id: Annotated[UUID, Field(alias='organizationId')]
    """
    The organization that owns this participant record.
    """
    type: Type2
    """
    Participant role: `user` = end-user, `ai-agent` = smooth-operator agent, `human-agent` = live support agent.
    """
    external_id: Annotated[str | None, Field(alias='externalId')] = None
    """
    External identity (e.g. Supabase auth user UUID) for authenticated participants.
    """
    internal_id: Annotated[str | None, Field(alias='internalId')] = None
    """
    Internal system identifier (e.g. agent UUID from the agents table).
    """
    browser_fingerprint: Annotated[str | None, Field(alias='browserFingerprint')] = None
    """
    Browser fingerprint (ThumbmarkJS) for anonymous user identification.
    """
    browser_info: Annotated[dict[str, Any] | None, Field(alias='browserInfo')] = None
    """
    Parsed browser / device metadata collected at session start.
    """
    name: str
    """
    Display name for this participant.
    """
    email: EmailStr | None = None
    """
    Email address if known.
    """
    phone: str | None = None
    """
    Phone number in E.164 format if known.
    """
    crm_contact_id: Annotated[UUID | None, Field(alias='crmContactId')] = None
    """
    Foreign key into the CRM contacts table if this participant has been matched.
    """
    metadata_json: Annotated[dict[str, Any] | None, Field(alias='metadataJson')] = None
    """
    Arbitrary key/value metadata attached to this participant.
    """
    created_at: Annotated[AwareDatetime, Field(alias='createdAt')]
    """
    ISO 8601 timestamp when the participant record was created.
    """
    updated_at: Annotated[AwareDatetime, Field(alias='updatedAt')]
    """
    ISO 8601 timestamp when the participant record was last updated.
    """


class Session(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    session_id: Annotated[UUID, Field(alias='sessionId')]
    """
    Unique session identifier.
    """
    conversation_id: Annotated[UUID, Field(alias='conversationId')]
    """
    The conversation this session is attached to.
    """
    organization_id: Annotated[UUID, Field(alias='organizationId')]
    """
    The organization that owns this session. Mirrors `organizationId` on the conversation, participants, and messages so org-scoping is uniform across every domain type and storage backends can write the session's org directly.
    """
    agent_id: Annotated[UUID, Field(alias='agentId')]
    """
    The agent handling this session.
    """
    agent_name: Annotated[str, Field(alias='agentName')]
    """
    Human-readable display name of the agent.
    """
    user_participant_id: Annotated[UUID, Field(alias='userParticipantId')]
    """
    The participant record representing the end user in this session.
    """
    agent_participant_id: Annotated[UUID, Field(alias='agentParticipantId')]
    """
    The participant record representing the AI agent in this session.
    """
    thread_id: Annotated[str, Field(alias='threadId')]
    """
    smooth-operator workflow thread identifier. Used to resume agent state across turns and process restarts. Stored as `langgraph_thread_id` in the database for historical reasons.
    """
    status: Status | None = None
    """
    Lifecycle status of the session.
    """
    token_count: Annotated[int | None, Field(alias='tokenCount', ge=0)] = None
    """
    Cumulative token count consumed in this session.
    """
    message_count: Annotated[int | None, Field(alias='messageCount', ge=0)] = None
    """
    Number of messages exchanged in this session.
    """
    metadata: dict[str, Any] | None = None
    """
    Arbitrary key/value metadata attached to this session (e.g. browser info, campaign source).
    """
    created_at: Annotated[AwareDatetime | None, Field(alias='createdAt')] = None
    """
    ISO 8601 timestamp when the session was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias='updatedAt')] = None
    """
    ISO 8601 timestamp when the session was last updated.
    """
    ended_at: Annotated[AwareDatetime | None, Field(alias='endedAt')] = None
    """
    ISO 8601 timestamp when the session ended, or null if still active.
    """
    last_activity_at: Annotated[AwareDatetime | None, Field(alias='lastActivityAt')] = (
        None
    )
    """
    ISO 8601 timestamp of the most recent activity (message, keepalive, etc.).
    """


class GetMessagesResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    messages: list[ConversationMessage]
    """
    Ordered list of messages (newest-first up to `limit`).
    """
    next_cursor: Annotated[str | None, Field(alias='nextCursor')] = None
    """
    Opaque cursor naming the oldest message in this page. Pass it as the next request's `cursor` to fetch the page before this one. Present (non-null) if and only if `hasMore` is true.
    """
    has_more: Annotated[bool, Field(alias='hasMore')]
    """
    True if more messages exist before the oldest message in this page — equivalently, if `nextCursor` is non-null.
    """


class SendMessageResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    message_id: Annotated[UUID, Field(alias='messageId')]
    """
    ID of the agent's response message as persisted to the database.
    """
    response: GeneralAgentResponse
    """
    Structured agent response.
    """
    needs_escalation: Annotated[bool, Field(alias='needsEscalation')]
    """
    True if the agent flagged this turn for human escalation.
    """
    escalation_reason: Annotated[str | None, Field(alias='escalationReason')] = None
    """
    Human-readable reason when `needsEscalation` is true.
    """
    directive: dict[str, Any] | None = None
    """
    An optional client-side directive the agent emitted for this turn (e.g. a navigation or view-application instruction). Opaque at the protocol layer — like `response`, the concrete shape (Navigate / ApplyView / …) is owned by the host client and validated there. Absent when the turn produced no directive. Last-write-wins when multiple were emitted.
    """


class MessageContent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    items: list[ContentItem] | None = None
    """
    Ordered list of content items that make up this message.
    """
    text: str | None = None
    """
    Convenience flat-text representation of the message (populated for simple text-only messages).
    """
    structured_response: Annotated[
        dict[str, Any] | None, Field(alias='structuredResponse')
    ] = None
    """
    Structured agent response payload. Shape varies by agent template.
    """


class Message(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: UUID
    """
    Unique message identifier.
    """
    external_id: Annotated[str | None, Field(alias='externalId')] = None
    """
    ID assigned by an external platform (e.g. a Twilio SID or Messenger message id).
    """
    organization_id: Annotated[UUID | None, Field(alias='organizationId')] = None
    """
    The organization that owns this message.
    """
    conversation_id: Annotated[UUID | None, Field(alias='conversationId')] = None
    """
    The conversation this message belongs to.
    """
    direction: Direction
    """
    Message direction relative to the platform: `inbound` = from user/external, `outbound` = from agent/platform.
    """
    content: MessageContent
    """
    The message payload.
    """
    from_: Annotated[From1 | None, Field(alias='from')] = None
    """
    Abbreviated sender descriptor (wire shape used in API responses; full participant data lives in domain/participant.schema.json).
    """
    to: To1 | None = None
    """
    Abbreviated recipient descriptor.
    """
    metadata_json: Annotated[dict[str, Any] | None, Field(alias='metadataJson')] = None
    """
    Arbitrary key/value metadata attached to this message.
    """
    analytics_json: Annotated[dict[str, Any] | None, Field(alias='analyticsJson')] = (
        None
    )
    """
    Analytics data associated with this message (e.g. sentiment scores, token counts).
    """
    created_at: Annotated[AwareDatetime, Field(alias='createdAt')]
    """
    ISO 8601 timestamp when the message was created.
    """
    updated_at: Annotated[AwareDatetime | None, Field(alias='updatedAt')] = None
    """
    ISO 8601 timestamp when the message was last updated.
    """
